server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/smoothsql?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: gy920689154
    driver-class-name: com.mysql.cj.jdbc.Driver

# MyBatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.smoothsql.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# Langchain4j配置
langchain4j:
  open-ai:
    chat-model:
      api-key: ${OPENAI_API_KEY:sk-197783824a45411fbbe712466fcf4234}
      model-name: deepseek-chat
      max-tokens: 2000
      temperature: 0.1

logging:
  level:
    # 应用程序日志级别
    com.smoothsql: info
    com.smoothsql.controller: info
    com.smoothsql.service: info
    
    # 数据库相关日志
    org.mybatis: debug
    com.smoothsql.mapper: debug
    org.springframework.jdbc: info
    
    # AI模型日志
    dev.langchain4j: info
    
    # Spring框架日志
    org.springframework.web: info
    org.springframework.security: warn
    
    # 根日志级别
    root: info
  
  # 日志格式配置
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  
  # 日志文件配置（可选）
  file:
    name: logs/smooth-sql.log
    max-size: 10MB
    max-history: 30